using Newtonsoft.Json;

namespace BoxApi.V2.Model
{
    /// <summary>
    ///     Comments are messages generated by Box users. Each message is tied to specific files or discussions. You can create comments independently or create them as responses to other comments.
    /// </summary>
    public class Comment : ModifiableEntity
    {
        /// <summary>
        ///     Whether or not this comment is a reply to another comment
        /// </summary>
        [JsonProperty(PropertyName = "is_reply_comment")]
        public bool IsReplyComment { get; set; }

        /// <summary>
        ///     The comment text
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        ///     The string representing the comment text with @mentions included. @mention format is @[id:username]. Field is not included by default.
        /// </summary>
        [JsonProperty(PropertyName = "tagged_message")]
        public string TaggedMessage { get; set; }


        /// <summary>
        ///     The object this comment was placed on
        /// </summary>
        public Entity Item { get; set; }

        /// <summary>
        ///     A unique ID for use with the /events endpoint
        /// </summary>
        public string SequenceId { get; set; }
    }
}